const kinds = [
  "Amuse-bouches",
  "Amuse-gueules",
  "Arancini",
  "Assiette",
  "Aumônières",
  "Axoa",
  "Bagel",
  "Ballotines",
  "Ballotins",
  "Bánh Canh",
  "Bánh Tôm",
  "Barbecue",
  "Beignets",
  "Bibimbap",
  "Biscuits",
  "Blanc-manger",
  "Blanquette",
  "Bolognaise",
  "Börek",
  "Bouchées",
  "Bouillabaisse",
  "Bouillon",
  "Boulettes",
  "Brandade",
  "Brasucade",
  "Brioche",
  "Brochettes",
  "Brownie",
  "Bruschetta",
  "Burger",
  "Cake",
  "Canapés",
  "Caquelons",
  "Carpaccio",
  "Casserole",
  "Cassolette",
  "Cassoulet",
  "Ceviche",
  "Chakchouka",
  "Chapalele",
  "Cheesecake",
  "Chips",
  "Chorba",
  "Churros",
  "Clafoutis",
  "Cocotte",
  "Colombo",
  "Compote",
  "Compotée",
  "Conchiglioni",
  "Confit",
  "Confiture",
  "Consommé",
  "Cookies",
  "Couscous",
  "Crackers",
  "Crème",
  "Crèpes",
  "Crépinettes",
  "Cromesquis",
  "Croquettes",
  "Crostinis",
  "Crumble",
  "Curry",
  "Dahl",
  "Daube",
  "Écrasé",
  "Effiloché",
  "Empanadas",
  "Espuma",
  "Estouffade",
  "Fabada",
  "Farçou",
  "Feijoada",
  "Financiers",
  "Flammekueche",
  "Focaccia",
  "Fondant",
  "Fondue",
  "Fougasse",
  "Fricassée",
  "Frites",
  "Frittata",
  "Fritti misti",
  "Fritures",
  "Fromage",
  "Fugazzeta",
  "Galantine",
  "Galette",
  "Garbure",
  "Gargoulette",
  "Gaspacho",
  "Gâteau",
  "Gelée",
  "Gnocchis",
  "Goulash",
  "Gözleme",
  "Gratin",
  "Gravlax",
  "Grillades",
  "Gua Bao",
  "Guacamole",
  "Gyozas",
  "Haché",
  "Hachis",
  "Hamburger",
  "Houmous",
  "Jambalaya",
  "Jardinière",
  "Katsudon",
  "Kebab",
  "Khao Phat",
  "Kimchi",
  "Korma",
  "Kouign Amann",
  "Lasagnes",
  "Macarons",
  "Mafé",
  "Marinade",
  "Marmite",
  "Méchoui",
  "Mejadra",
  "Menemen",
  "Mezzé",
  "Mi-cuit",
  "Mijoté",
  "Millefeuille",
  "Minestrone",
  "Mini-blinis",
  "Mochis",
  "Moussaka",
  "Mousse",
  "Mousseline",
  "Muffins",
  "Naan",
  "Nachos",
  "Nems",
  "Nuggets",
  "Okonomiyaki",
  "Omelette",
  "Onigiri",
  "Osso Buco",
  "Oyakodon",
  "Pad Thai",
  "Paëlla",
  "Pain surprise",
  "Pancakes",
  "Panettone",
  "Panna Cotta",
  "Papillottes",
  "Parillada",
  "Parmentier",
  "Pastilla",
  "Pâté",
  "Paupiettes",
  "Pho",
  "Pickles",
  "Pierrade",
  "Pintxos",
  "Pizza",
  "Plancha",
  "Planche",
  "Poêlée",
  "Poke Bowl",
  "Pot-au-feu",
  "Potage",
  "Potée",
  "Potjevleesch",
  "Potjiekos",
  "Profiteroles",
  "Purée",
  "Quiche",
  "Ragoût",
  "Ramen",
  "Ratatouille",
  "Ravioles",
  "Reblochonnade",
  "Rillettes",
  "Risotto",
  "Rôti",
  "Rougail",
  "Rouille",
  "Roulés",
  "Sacristains",
  "Salade",
  "Samoussas",
  "Sandwich",
  "Sashimis",
  "Sauté",
  "Shakshuka",
  "Shortbread",
  "Sirop",
  "Smoothie",
  "Snack",
  "Sorbet",
  "Soubressade",
  "Soufflé",
  "Soupe froide",
  "Soupe",
  "Sticks",
  "Sushis",
  "Taboulé",
  "Tacos",
  "Tajine",
  "Takoyaki",
  "Tamales",
  "Tapas",
  "Tapenade",
  "Tartare",
  "Tarte",
  "Tartelettes",
  "Tartines",
  "Tataki",
  "Tempura",
  "Terrine",
  "Tian",
  "Tielles",
  "Timbales",
  "Tiramisu",
  "Toasts",
  "Tortilla",
  "Tourte",
  "Tourtière",
  "Tzatziki",
  "Udon",
  "Velouté",
  "Verrines",
  "Vol-au-vent",
  "Waterzooi",
  "Wok",
  "Yakitori",
  "Zabayon",
];

const ingredients = [
  ["Abondance AOP", "d'", "à l'"],
  ["Abricot", "d'", "à l'"],
  ["Agneau épicé", "d'", null],
  ["Agrumes", "d'", "aux"],
  ["Ail confit", null, "à l'"],
  ["Ail des ours", null, "à l'"],
  ["Ail", null, "à l'"],
  ["Ailes de poulet grillées", "d'", null],
  ["Aïoli", null, "à l'"],
  ["Algues nori", null, "aux"],
  ["Algues Wakamé", "de", "aux"],
  ["Amandes amères", "d'", "aux"],
  ["Amandes", "d'", "aux"],
  ["Ananas", "d'", "à l'"],
  ["Anchois", "d'", "aux"],
  ["Andouille de Guéméné", "d'", "à l'"],
  ["Andouille de Vire", "d'", "à l'"],
  ["Andouillette de Troyes", "d'", "à l'"],
  ["Aneth", null, "à l'"],
  ["Anguille fumée", "d'", "à l'"],
  ["Angus", "d'", null],
  ["Anis étoilé", null, "à l'"],
  ["Anisette", null, "à l'"],
  ["Araignée de mer", "d'", null],
  ["Artichauts", "d'", "aux"],
  ["Asperges vertes", "d'", "aux"],
  ["Aubergines", "d'", "aux"],
  ["Avocats", "d'", "aux"],
  ["Avoine", "d'", "à l'"],
  ["Badiane", null, "à la"],
  ["Baies de genièvre", null, "aux"],
  ["Baies roses", null, "aux"],
  ["Bananes plantain", "de", "aux"],
  ["Bananes vertes", "de", "aux"],
  ["Bananes", "de", "aux"],
  ["Bar", "de", null],
  ["Barberries", null, "aux"],
  ["Basilic Thaï", null, "au"],
  ["Basilic", null, "au"],
  ["Batavia", "de", "à la"],
  ["Beaufort", "de", "au"],
  ["Bergamotte", null, "à la"],
  ["Betteraves", "de", "aux"],
  ["Beurre blanc miso", null, "au"],
  ["Beurre salé", null, "au"],
  ["Biche", "de", null],
  ["Bière", null, "à la"],
  ["Bigorneaux", "de", "aux"],
  ["Blettes", "de", "aux"],
  ["Bleu des causses", "de", "au"],
  ["Bleuets", "de", "aux"],
  ["Bœuf de Kobe", "de", null],
  ["Bœuf", "de", null],
  ["Boudins Blancs", "de", null],
  ["Boulghour", "de", "au"],
  ["Bourbon", null, "au"],
  ["Bourrache", null, "à la"],
  ["Bretzels", "de", "aux"],
  ["Brocciù", "de", "au"],
  ["Brochet", "de", null],
  ["Brocolis grillés", "de", "aux"],
  ["Bulots", "de", "aux"],
  ["Burrata", "de", "à la"],
  ["Cabécou", "de", "au"],
  ["Cabillau", "de", null],
  ["Cacahuètes", "de", "aux"],
  ["Cacao", "de", "au"],
  ["Café", null, "au"],
  ["Caille", "de", null],
  ["Calamar", "de", null],
  ["Camembert rôti", "de", "au"],
  ["Camembert", "de", "au"],
  ["Canard", "de", null],
  ["Cantal", "de", "au"],
  ["Câpres", null, "aux"],
  ["Caramel beurre salé", null, "au"],
  ["Caramel", null, "au"],
  ["Carottes", "de", "aux"],
  ["Carpe", "de", null],
  ["Carrelet", "de", null],
  ["Cassonade", null, "à la"],
  ["Caviar Sevruga", "de", "au"],
  ["Cédrat confit", "de", "au"],
  ["Céleri rémoulade", "de", "au"],
  ["Céleri", "de", "au"],
  ["Cèpes", "de", "aux"],
  ["Cerf", "de", null],
  ["Cerfeuil", null, "au"],
  ["Cerises noires", "de", "aux"],
  ["Cerises", "de", "aux"],
  ["Cervelas", "de", "au"],
  ["Cervelle", "de", null],
  ["Chablis", null, "au"],
  ["Champagne", null, "au"],
  ["Champignons de Paris", "de", "aux"],
  ["Champignons Matsutaké", "de", "aux"],
  ["Champignons", "de", "aux"],
  ["Chapon", "de", null],
  ["Chataîgnes grillées", "de", "aux"],
  ["Cheddar", "de", "au"],
  ["Chénopode blanc", null, "au"],
  ["Chèvre cendré", "de", "au"],
  ["Chèvre frais", "de", "au"],
  ["Chevreuil", "de", null],
  ["Chevrotin des Aravis", "de", "au"],
  ["Chianti", null, "au"],
  ["Chicons", "de", "aux"],
  ["Chicorée", null, "à la"],
  ["Chipolatas", "de", "aux"],
  ["Chocolat au lait", "de", "au"],
  ["Chocolat blanc", "de", "au"],
  ["Chocolat noir", "de", "au"],
  ["Chocolat", "de", "au"],
  ["Chou Romanesco", "de", "au"],
  ["Chou rouge", "de", "au"],
  ["Chou-fleur", "de", "au"],
  ["Chou", "de", "au"],
  ["Choucroute", "de", "à la"],
  ["Choux de Bruxelles", "de", "aux"],
  ["Ciboulette", null, "à la"],
  ["Citron vert", "de", "au"],
  ["Citron", "de", "au"],
  ["Citronnelle", null, "à la"],
  ["Citrons confits", "de", "aux"],
  ["Citrouille", "de", "à la"],
  ["Clémentines", "de", "aux"],
  ["Clous de Girofle", null, "aux"],
  ["Cochon de lait", "de", "au"],
  ["Cochonailles", "de", null],
  ["Cocos de Paimpol", "de", "aux"],
  ["Cœurs de canard", "de", "aux"],
  ["Cointreau", null, "au"],
  ["Colin", "de", null],
  ["Combava", null, "au"],
  ["Comté", "de", "au"],
  ["Concombre de mer", "de", "au"],
  ["Conques", "de", "aux"],
  ["Coppa", "de", "à la"],
  ["Coquillages", "de", "aux"],
  ["Coquilles lutées", "de", "en"],
  ["Coquillettes", "de", "aux"],
  ["Coriandre", null, "à la"],
  ["Cornichons", null, "aux"],
  ["Côtes de bœuf", "de", null],
  ["Côtes de marcassin", "de", null],
  ["Côtes de porc", "de", null],
  ["Coulommiers", "de", "au"],
  ["Courge Butternut", "de", "à la"],
  ["Courgettes", "de", "aux"],
  ["Couteaux", "de", "aux"],
  ["Crabe", "de", "au"],
  ["Crème Chantilly", null, "à la"],
  ["Crème fraîche", null, "à la"],
  ["Cresson", "de", "au"],
  ["Crevettes", "de", "aux"],
  ["Crottin de Chavignol", "de", "au"],
  ["Croûtons", null, "aux"],
  ["Crustacés", "de", "aux"],
  ["Cuisses de canard", "de", null],
  ["Cuisses de grenouille", "de", null],
  ["Cumin", null, "au"],
  ["Curcuma", null, "au"],
  ["Curry", null, "au"],
  ["Dattes", "de", "aux"],
  ["Dinde", "de", null],
  ["Dindonneau", "de", null],
  ["Diots", "de", null],
  ["Dorade", "de", null],
  ["Durian", "de", "au"],
  ["Eau de vie", null, "à l'"],
  ["Échalottes confites", null, "aux"],
  ["Échalottes", null, "aux"],
  ["Écrevisses", "d'", "aux"],
  ["Edamames", null, "aux"],
  ["Emmental", "d'", "à l'"],
  ["Endives caramélisées", "d'", "aux"],
  ["Eperlan", "d'", null],
  ["Épi de maïs", "d'", null],
  ["Épices", null, "aux"],
  ["Épinards", "d'", "aux"],
  ["Époisse", null, "à l'"],
  ["Esturgeon", "d'", null],
  ["Étoile de mer", "d'", null],
  ["Faisan", "de", null],
  ["Feijoas", "de", "aux"],
  ["Fenouil", "de", "au"],
  ["Fettuccine", "de", "aux"],
  ["Feuilles de vigne", "de", "aux"],
  ["Fèves de cacao", "de", "aux"],
  ["Fèves", "de", "aux"],
  ["Figatelle", "de", "à la"],
  ["Figues de Barbarie", "de", "aux"],
  ["Figues", "de", "aux"],
  ["Filet d'églefin", "de", null],
  ["Filet de bœuf", "de", null],
  ["Filet de canard", "de", null],
  ["Filet mignon", "de", null],
  ["Flageolets", "de", "aux"],
  ["Fleur de sel", null, "à la"],
  ["Fleurs de montagne", null, "aux"],
  ["Fleurs de courgette", "de", "aux"],
  ["Foie d'oie", "de", "au"],
  ["Foie de veau", "de", "au"],
  ["Foie gras", "de", "au"],
  ["Fourme d’Ambert", "de", "à la"],
  ["Fraises", "de", "aux"],
  ["Fraises des bois", "de", "aux"],
  ["Framboises", "de", "aux"],
  ["Fromage de tête", "de", null],
  ["Fruits confits", "de", "aux"],
  ["Fruits de la Passion", "de", "aux"],
  ["Fruits secs fumés-sucrés", "de", "aux"],
  ["Gambas", "de", "aux"],
  ["Gésiers d'oie", "de", "aux"],
  ["Gingembre confit", null, "au"],
  ["Gingembre", null, "au"],
  ["Girolles", "de", "aux"],
  ["Gîte à la noix", "de", null],
  ["Gnocchis", "de", "aux"],
  ["Gomasio", null, "au"],
  ["Gorgonzola", "de", "au"],
  ["Gouda vieux", "de", "au"],
  ["Gouda", "de", "au"],
  ["Gousses d'ail confites", null, "aux"],
  ["Goyave", "de", "à la"],
  ["Graines de chia", null, "aux"],
  ["Graines de courge", null, "aux"],
  ["Graines de lin", null, "aux"],
  ["Graines", null, "aux"],
  ["Grains de caviar", "de", "aux"],
  ["Grains de Grenade", "de", "aux"],
  ["Graisse de canard", null, "à la"],
  ["Gruyère", "de", "au"],
  ["Haddock", "de", "au"],
  ["Harengs fumés", "de", null],
  ["Haricots blancs", "de", "aux"],
  ["Haricots rouges", "de", "aux"],
  ["Haricots verts", "de", "aux"],
  ["Harissa", null, "à la"],
  ["Herbes fraîches", null, "aux"],
  ["Homard bleu", "de", "au"],
  ["Houmous", "de", "au"],
  ["Huile d'olive", null, "à l'"],
  ["Huile de coco", null, "à l'"],
  ["Huile de sésame", null, "à l'"],
  ["Huîtres", "d'", "aux"],
  ["Huîtres chaudes", "d'", "aux"],
  ["Huîtres rôties", "d'", "aux"],
  ["Jambon Bellota", "de", "au"],
  ["Jambon braisé", "de", "au"],
  ["Jambon de Bayonne", "de", "au"],
  ["Jambon de Chalosse", "de", "au"],
  ["Jambon fumé de Vendée", "de", "au"],
  ["Jambon Noir de Bigorre", "de", "au"],
  ["Jambon Pata Negra", "de", "au"],
  ["Jambon", "de", "au"],
  ["Jambonneau", "de", "au"],
  ["Jarret de cochon", "de", null],
  ["Kakis", "de", "aux"],
  ["Kéfir", null, "au"],
  ["Ketchup", null, "au"],
  ["Kiwis", "de", "aux"],
  ["Knacks", "de", null],
  ["Kombucha", null, "au"],
  ["Kumquats", "de", "aux"],
  ["Lait d'amande", null, "au"],
  ["Lait d'ânesse", null, "au"],
  ["Lait de brebis", null, "au"],
  ["Lait de chèvre", null, "au"],
  ["Lait de coco", null, "au"],
  ["Lait de soja", null, "au"],
  ["Lait", "de", "au"],
  ["Laitue", "de", "à la"],
  ["Langouste", "de", "à la"],
  ["Langoustines", "de", "aux"],
  ["Langue de bœuf", "de", null],
  ["Lapin", "de", null],
  ["Lard de Colonnata", null, "au"],
  ["Lard", null, "au"],
  ["Légumes nouveaux", "de", "aux"],
  ["Lentilles corail", "de", "aux"],
  ["Lentilles vertes", "de", "aux"],
  ["Lieu jaune", "de", null],
  ["Lieu noir", "de", null],
  ["Lièvre", "de", null],
  ["Livarot", "de", "au"],
  ["Macaroni", "de", "aux"],
  ["Mâche", "de", "à la"],
  ["Magret de canard", "de", null],
  ["Maïs", "de", "au"],
  ["Mandarines", "de", "aux"],
  ["Mangoustan", "de", "au"],
  ["Mangue", "de", "à la"],
  ["Manouri", "de", "au"],
  ["Maquereaux", "de", "aux"],
  ["Marjolaine", null, "à la"],
  ["Maroilles", "de", "au"],
  ["Marrons glacés", "de", "aux"],
  ["Marrons grillés", "de", "aux"],
  ["Marrons", "de", "aux"],
  ["Maté", null, "au"],
  ["Mayonnaise de Dijon", null, "à la"],
  ["Mélisse", null, "à la"],
  ["Melon charentais", "de", "au"],
  ["Melon d'eau", "de", "au"],
  ["Menthe fraîche", "de", "à la"],
  ["Merguez", "de", "aux"],
  ["Merlan", "de", null],
  ["Merlu de ligne", "de", null],
  ["Miel", null, "au"],
  ["Mimolette", "de", "à la"],
  ["Miso", null, "au"],
  ["Mont d’Or", "de", "au"],
  ["Morbier", "de", "au"],
  ["Morilles", "de", "aux"],
  ["Mortadelle", "de", "à la"],
  ["Morue", "de", "à la"],
  ["Moules marinières", "de", "aux"],
  ["Mousserons", "de", "aux"],
  ["Moutarde au miel", null, "à la"],
  ["Moutarde de Dijon", null, "à la"],
  ["Mouton", "de", null],
  ["Mozzarella", "de", "à la"],
  ["Munster", "de", "au"],
  ["Murène", "de", null],
  ["Museau de bœuf", "de", null],
  ["Myrtilles", "de", "aux"],
  ["Navets Boule d'Or", "de", "aux"],
  ["Navets", "de", "aux"],
  ["Noisettes", null, "aux"],
  ["Noix de cajou", null, "aux"],
  ["Noix de coco", "de", "à la"],
  ["Noix de macadamia", null, "aux"],
  ["Noix de muscade", null, "à la"],
  ["Noix du Brésil", null, "aux"],
  ["Noix", null, "aux"],
  ["Nougat de Montélimar", "de", "au"],
  ["Nuoc Mam", null, "au"],
  ["Œufs brouillés", "d'", "aux"],
  ["Œufs d'Autruche", "d'", null],
  ["Œufs de caille", "d'", "aux"],
  ["Œufs de lump", "d'", "aux"],
  ["Œufs de truite", "d'", "aux"],
  ["Œufs", "d'", "aux"],
  ["Oie", "d'", null],
  ["Oignons frits", null, "aux"],
  ["Oignons marinés", "d'", "aux"],
  ["Oignons", "d'", "aux"],
  ["Olives", null, "aux"],
  ["Olives noires de Nyons", null, "aux"],
  ["Onglet", "d'", null],
  ["Orange", null, "à l'"],
  ["Oranges amères", "d'", "aux"],
  ["Oranges confites", "d'", "aux"],
  ["Origan", null, "à l'"],
  ["Orties", null, "aux"],
  ["Ortolans", "d'", null],
  ["Oursins", "d'", "aux"],
  ["Pain de campagne", "de", "au"],
  ["Palourdes", "de", "aux"],
  ["Pamplemousse", "de", "au"],
  ["Panais", "de", "aux"],
  ["Papaye", "de", "à la"],
  ["Paprika fumé", null, "au"],
  ["Paprika", null, "au"],
  ["Parmesan", "de", "au"],
  ["Pastèque", "de", "à la"],
  ["Pastis", null, "au"],
  ["Pastrami", "de", "au"],
  ["Patates douces", "de", "aux"],
  ["Patates", "de", "aux"],
  ["Pavot", null, "au"],
  ["Pecorino Stagionato", null, "au"],
  ["Pépites de Foie Gras", null, "aux"],
  ["Persil tubéreux", null, "au"],
  ["Petites rattes du Touquet", "de", "aux"],
  ["Petits Boudins Antillais", "de", "aux"],
  ["Petits oignons nouveaux", "de", "aux"],
  ["Petits pois", "de", "aux"],
  ["Pétoncles", "de", "aux"],
  ["Pieds de porc", "de", "aux"],
  ["Pieuvre", "de", null],
  ["Pigeon", "de", null],
  ["Pigeonneau", "de", null],
  ["Pignons de pin", "de", "aux"],
  ["Pilons de poulet", "de", null],
  ["Piment d'Espelette", null, "au"],
  ["Piment de Cayenne", null, "au"],
  ["Piment", null, "au"],
  ["Pineau des Charentes", null, "au"],
  ["Pintade", "de", null],
  ["Pissenlit", null, "au"],
  ["Pistaches", null, "aux"],
  ["Plat de côte", "de", null],
  ["Poires", "de", "aux"],
  ["Poireaux", "de", "aux"],
  ["Pois chiches", "de", "aux"],
  ["Pois", "de", "aux"],
  ["Poisson cru", "de", "au"],
  ["Poitrine fumée", "de", "à la"],
  ["Poivre de Kampot", null, "au"],
  ["Poivre de Sichuan", null, "au"],
  ["Poivre de Timut", null, "au"],
  ["Poivre vert", null, "au"],
  ["Poivrons anciens", "de", "aux"],
  ["Poivrons grillés", "de", "aux"],
  ["Polenta", "de", "à la"],
  ["Pomelo", "de", "au"],
  ["Pommes de terre", "de", "aux"],
  ["Pommes de terre Grenaille", "de", "aux"],
  ["Pommes", "de", "aux"],
  ["Pont l’Évêque", "de", "au"],
  ["Porc noir de Bigorre", "de", null],
  ["Porto", null, "au"],
  ["Potimarron", "de", "au"],
  ["Potiron", "de", "au"],
  ["Poularde", "de", null],
  ["Poule", "de", null],
  ["Poulet croustillant", "de", null],
  ["Poulet tandoori", "de", null],
  ["Poulet", "de", "au"],
  ["Poulpe", "de", null],
  ["Quatre fromages", null, "aux"],
  ["Quatre-épices", null, "au"],
  ["Queue de bœuf", "de", null],
  ["Quinoa", "de", "au"],
  ["Raclette", "de", "à la"],
  ["Radis noir", "de", "au"],
  ["Radis", "de", "aux"],
  ["Raie", "de", null],
  ["Raifort", null, "au"],
  ["Raisin", null, "au"],
  ["Raisins secs", null, "aux"],
  ["Ramboutan", "de", "au"],
  ["Ras el-hanout", null, "au"],
  ["Rascasse", "de", null],
  ["Ravioli", "de", "aux"],
  ["Reblochon fermier", "de", "au"],
  ["Requin", "de", null],
  ["Rhubarbe", "de", "à la"],
  ["Rhum", null, "au"],
  ["Ricotta", "de", "à la"],
  ["Riesling", null, "au"],
  ["Rigatonis", "de", "aux"],
  ["Ris de veau", "de", "aux"],
  ["Riz brun", "de", "au"],
  ["Riz épicé", "de", "au"],
  ["Riz fumé", "de", "au"],
  ["Riz noir", "de", "au"],
  ["Riz vermicelle", "de", "au"],
  ["Riz", "de", "au"],
  ["Rocamadour", "de", "au"],
  ["Rognons", "de", "aux"],
  ["Rollmops", "de", "aux"],
  ["Romarin", null, "au"],
  ["Roquefort", "de", "au"],
  ["Rosette de Lyon", "de", "à la"],
  ["Rôti de dindonneau", "de", null],
  ["Rouget", "de", null],
  ["Rumsteak", "de", "au"],
  ["Rutabagas", "de", "aux"],
  ["Safran", null, "au"],
  ["Saindoux", null, "au"],
  ["Saint-Félicien", "de", "au"],
  ["Saint-Marcelin", "de", "au"],
  ["Saint-Nectaire fermier", "de", "au"],
  ["Saint-Pierre", "de", null],
  ["Salami", "de", "au"],
  ["Salsifis", "de", "aux"],
  ["Sanglier", "de", null],
  ["Sardines", "de", "aux"],
  ["Sauce Barbecue", null, "à la"],
  ["Sauce brune", null, "à la"],
  ["Sauce soja", null, "à la"],
  ["Sauce Sriracha", null, "à la"],
  ["Sauce Worcestershire", null, "à la"],
  ["Saucisse de canard", "de", null],
  ["Saucisse", "de", "à la"],
  ["Saucisses aux herbes", "de", null],
  ["Saucisses Cocktail", "de", "aux"],
  ["Saucisses de Francfort", "de", "aux"],
  ["Saucisses de Morteau", "de", null],
  ["Saucisses de Strasbourg", "de", "aux"],
  ["Saucisson à l'ail", "de", "au"],
  ["Saucisson de taureau", "de", "au"],
  ["Sauge", null, "à la"],
  ["Saumon fumé", "de", "au"],
  ["Sauternes", null, "au"],
  ["Scampis", "de", "aux"],
  ["Scarmoza", "de", "à la"],
  ["Scarole", "de", "à la"],
  ["Schnitzel", "de", null],
  ["Seiche", "de", null],
  ["Sel & Poivre", null, "au"],
  ["Sel himalayen", null, "au"],
  ["Serrano", "de", "au"],
  ["Sésame doré", null, "au"],
  ["Sésame noir", null, "au"],
  ["Sésame", null, "au"],
  ["Sirop d’érable", null, "au"],
  ["Sirop de Liège", null, "au"],
  ["Sole", "de", null],
  ["Spaghettis", "de", "aux"],
  ["Spätzle", "de", "aux"],
  ["Sucre brun", null, "au"],
  ["Tabasco", null, "au"],
  ["Tagliatelles", "de", "aux"],
  ["Tahini", null, "au"],
  ["Taillerins", "de", "aux"],
  ["Tamarin", "de", "au"],
  ["Taureau de Camargue", "de", null],
  ["Thé vert", "de", "au"],
  ["Thon rouge", "de", "au"],
  ["Thym bio", null, "au"],
  ["Tofu", "de", "au"],
  ["Tofu fumé", "de", "au"],
  ["Tomate", "de", "à la"],
  ["Tomates confites", "de", "aux"],
  ["Tomates noires de Crimée", "de", "aux"],
  ["Tomates séchées", "de", "aux"],
  ["Tome des Bauges AOP", "de", "à la"],
  ["Tomme Crayeuse Fermière", "de", "à la"],
  ["Tomme de Montagne", "de", "à la"],
  ["Topinambours", "de", "aux"],
  ["Tortellini", "de", "aux"],
  ["Travers de porc", "de", null],
  ["Tripes", "de", "aux"],
  ["Trompettes de la mort", "de", "aux"],
  ["Truffe blanche d'Alba", null, "à la"],
  ["Truffe noire du Périgord", null, "à la"],
  ["Truite saumonnée", "de", null],
  ["Turbot", "de", null],
  ["Veau de lait de Corrèze", "de", null],
  ["Verveine", null, "à la"],
  ["Viande des Grisons", "de", "à la"],
  ["Viande hachée", "de", "à la"],
  ["Viandox", null, "au"],
  ["Vinaigre balsamique", null, "au"],
  ["Vinaigre de cidre", null, "au"],
  ["Vinaigre de Modène", null, "au"],
  ["Vinaigrette", null, "à la"],
  ["Vodka", null, "à la"],
  ["Volaille", "de", null],
  ["Wasabi", null, "au"],
  ["Whisky", null, "au"],
  ["Xérès", null, "au"],
  ["Yaourt", "de", "au"],
];

function pickOne(list, exclude = []) {
  const idx = parseInt(Math.floor(Math.random() * list.length), 10);
  const pick = list[idx];
  return exclude.includes(pick) ? pickOne(list, pick) : pick;
}

function format(k, i1, i2, i3) {
  if (!i1[1] || !i2[2] || !i3[2]) {
    return null;
  } else {
    let customList = ["sauce", `et ${i3[2]}`];
    if (i3[1]) {
      customList = customList.concat([
        `en croûte ${i3[1]}`,
        `et éclats ${i3[1]}`,
        `et pépites ${i3[1]}`,
        `sur lit ${i3[1]}`,
      ]);
    }
    const custom = pickOne(customList);
    const full = Math.random() > 0.6 ? ` ${custom} ${i3[0]}` : "";
    return `${k} ${i1[1]} ${i1[0]} ${i2[2]} ${i2[0]}${full}`
      .replaceAll("' ", "’")
      .replaceAll("'", "’");
  }
}

function run() {
  const k = pickOne(kinds);
  const i1 = pickOne(ingredients);
  const i2 = pickOne(ingredients, [i1]);
  const i3 = pickOne(ingredients, [i1, i2]);
  const recipe = format(k, i1, i2, i3);
  return recipe ? { name: recipe, kind: k } : run();
}

export default {
  run,
};
